
name: build
env:
  APPLICATION_NAME : "calculator"
  DEPLOY_PACKAGE_NAME : "calculator-ver-${{github.sha}}" 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build-part 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check code style
        run: mvn -B checkstyle:checkstyle
      - name: Build with Maven
        run: mvn -Djar.finalName=${{env.APPLICATION_NAME}} -B clean verify
      - name: rename result
        run: mv ./target/calculator*.jar ./target/calculator-9989.jar
      - name: run test
        run: |
          ls -al ./target
          chmod +x ./test.sh
          ./test.sh
          ls -al ./target
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
         name: ${{env.DEPLOY_PACKAGE_NAME}}
         path: ./target/${{env.APPLICATION_NAME}}.jar

  publish:
    name: cd-part
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
         name: ${{env.DEPLOY_PACKAGE_NAME}}
#      - name: Display structure of downloaded files
#        run: ls -R
      - name: release packet
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: ./${{env.APPLICATION_NAME}}.jar
        
     
