
name: build
env:
  APPLICATION_NAME : "Calculator"
  DEPLOY_PACKAGE_NAME : "Calculator-ver-${{github.sha}}" 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: Check code style
#        run: mvn -B checkstyle:checkstyle
      - name: Build with Maven
        run: mvn -Djar.finalName=${{env.APPLICATION_NAME}} -B clean verify
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
         name: ${{env.DEPLOY_PACKAGE_NAME}}
         path: ./target/${{env.APPLICATION_NAME}}.jar

publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
         # Artifact name
         name: ${{env.DEPLOY_PACKAGE_NAME}}
      - name: Display structure of downloaded files
        run: ls -R
      - name: dictav/release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./release/${{env.DEPLOY_PACKAGE_NAME}}.jar
        
     
