
name: build
env:
  APPLICATION_NAME : "Calculator"
  DEPLOY_PACKAGE_NAME : "Calculator-{{ github.sha }}" 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: Check code style
#        run: mvn -B checkstyle:checkstyle
      - name: Build with Maven
        run: |
          mvn -Djar.finalName=${{ env.APPLICATION_NAME }} -B clean verify
          ls -al ./target
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

